### ISSUE TITLE
Gallery didn't occupy 100% width

### ISSUE THREAD

**Issue by jksenthilraja** [xremix/xGallerify#23]
Hi Guys,

Left alignment is perfect but right side alignment not perfect 20px to 30px gap is showing didn't occupy 100% of gallery, And I try to set margin left 20px of parent tag then to be stay the issue. How is fixed.

Or any other chance to increase width  5px  every items

**Comment by xremix** [comment]
Thank you for your input @jksenthilraja. Do you also have a code sample?

Thanks
Toni

**Comment by xremix** [comment]
@jksenthilraja could you please take a look at #26 and check if this version of _xGallerify_ is working for you?
And can you confirm that the alignment is 20px vs 30px and not 20px vs 28px? 

A code sample could help as well. You could also try to give your images itself a margin. Something like

```
<div id="photos">
   <div class="photo">
      <img style="margin:20px;" />
   </div>
</div>
```

**Comment by xremix** [comment]
@jksenthilraja 
`https://rawgit.com/xremix/xGallerify/fix-margin/dist/jquery.xgallerify.min.js`

**Comment by jksenthilraja** [comment]
thankyou @xremix

**Comment by jksenthilraja** [comment]
But Now a day's using this grid like

![mosaic-grid](https://cloud.githubusercontent.com/assets/17898179/18625909/4c6ceab8-7e6f-11e6-8031-0dc54f831c28.png)

this type available in our plugin............ @xremix

**Comment by JohnnyTheTank** [comment]
@jksenthilraja you could use this angular plugin: https://github.com/JohnnyTheTank/angular-bricklayer

**Comment by xremix** [comment]
@jksenthilraja this type of grid is not available in xGallerify. The goal of xGallerify is to show images in rows with a similar heights, to have a good balance between regular, portrait and panorama images. 

Otherwise I can just highly recommend what JohnnyTheTank posted above, if you want a different grid style.
PS: Keyword Masonry could also be interesting for you

**Comment by jksenthilraja** [comment]
Hi 
Which Pagination suitable for xGallerify

**Comment by xremix** [comment]
@jksenthilraja right now there is no functionality, but you could pretty simply implement one on your own.
In js you could add all your images of page 1 to a div and run `xGallerify()`. When the user clicks on the page 2 link you remove all the images of that div and add the new once, and run `xGallerify()` one more time. I have not planned that feature yet, because this does not fit to the approach of the gallery right now and can be implemented pretty easily as a user of the gallery.

**Comment by jksenthilraja** [comment]
Hi @xremix 

I am Get Plugin min.js from  
**https://rawgit.com/xremix/xGallerify/fix-margin/dist/jquery.xgallerify.min.js** 
for **remove right side space** it's working but problem is when i **resized browser** then **collapsed to Gallery** then how to solved it.

**Comment by xremix** [comment]
@jksenthilraja the 100% now is working way better with the version v0.1.2.
But there is still some issue with the scrollbar on macOS Safari, so I always have a 15px margin on both sides. I'll add an option to overwrite that, so you can have the 100% width anyways if wanted.

**Comment by xremix** [comment]
@jksenthilraja you can now set the gallery margin and have a 100% width:
```js
$('.photos').gallerify({
	margin:10,
       galleryMargin: 0,
	mode:'default'
});
```

But be aware there might be an rendering error on some `macOS Safari` versions.
