### ISSUE TITLE
Rotation of portrait-pictures

### ISSUE THREAD

**Issue by titom59280** [xremix/xGallerify#28]
Hello
I have a problem with portrait-pictures, these pictures rotate systematically 90° counterclockwise.

I wonder why this behavior because with 12 portrait-pictures, I have 4 rows of 3 pictures when I could have 3 rows of 4 pictures.

I put a capture to see by yourselves.
![issue](https://user-images.githubusercontent.com/7037603/27511503-0bff049c-5926-11e7-8a1b-04153278f193.PNG)

How can I stop this behavior in order to have the correct display of these pictures.

Thanks for you help

**Comment by xremix** [comment]
Hello @titom59280 , 
thanks a lot for reaching out to me on that issue!
I try to help as good as I can.
Strange, so far I can't imagine how this behavior can occur, or at least I can't imagine that the Gallery is making this issue.
Everything what the gallery is doing is setting some styles to align images next to each other and resizing the height and width of each single image.

Do you have some demo (jsfiddle or similar) to show how this issue occurs?

Maybe the issue is on a very different level. Often cameras (and specially smartphones) do always save images in landscape format. But they do also store the orientation / camera position in the exif data. And most of the software do rotate the image on their own, but browser just display it the way they get it and ignore all of the exif data.
Might that be the issue here?

Have fun using xGallery!

**Comment by titom59280** [comment]
Thanks for your answer.

Indeed, these pictures was taken with a smartphone, and that was the cause.

I tried with landscape pictures taken by a camera and this behavior does not occur.

For my usage it's fine because I wil not use the gallery with pictures taken by smartphone (it was just some test :) ).

Thanks anyway for your help and your quick response.

**Comment by xremix** [comment]
Sounds great @titom59280! Glad I could help you. Usually it should also work with portrait pictures as long as the pixels are really stored in portrait ratio. I also have a couple of them in my Demo:
https://rawgit.com/xremix/xGallerify/master/Demo.html

Let me know if there is anything else!
